set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]


set_property PACKAGE_PIN R3 [get_ports SYSCLK_P]
set_property IOSTANDARD LVDS_25 [get_ports SYSCLK_P]
set_property PACKAGE_PIN P3 [get_ports SYSCLK_N]
set_property IOSTANDARD LVDS_25 [get_ports SYSCLK_N]

set_property PACKAGE_PIN M26 [get_ports GPIO_LED_0]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_LED_0]
set_property PACKAGE_PIN T24 [get_ports GPIO_LED_1]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_LED_1]
set_property PACKAGE_PIN T25 [get_ports GPIO_LED_2]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_LED_2]
set_property PACKAGE_PIN R26 [get_ports GPIO_LED_3]
set_property IOSTANDARD LVCMOS33 [get_ports GPIO_LED_3]

set_property PACKAGE_PIN P6 [get_ports GPIO_SW_N]
set_property IOSTANDARD LVCMOS15 [get_ports GPIO_SW_N]
set_property PACKAGE_PIN T5 [get_ports GPIO_SW_S]
set_property IOSTANDARD SSTL15 [get_ports GPIO_SW_S]
set_property PACKAGE_PIN R5 [get_ports GPIO_SW_W]
set_property IOSTANDARD SSTL15 [get_ports GPIO_SW_W]
set_property PACKAGE_PIN U6 [get_ports GPIO_SW_C]
set_property IOSTANDARD SSTL15 [get_ports GPIO_SW_C]
set_property PACKAGE_PIN U5 [get_ports GPIO_SW_E]
set_property IOSTANDARD SSTL15 [get_ports GPIO_SW_E]

set_property PACKAGE_PIN P26 [get_ports PMOD_0]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD_0]
set_property PACKAGE_PIN T22 [get_ports PMOD_1]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD_1]
set_property PACKAGE_PIN R22 [get_ports PMOD_2]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD_2]
set_property PACKAGE_PIN T23 [get_ports PMOD_3]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD_3]

set_property PACKAGE_PIN R8 [get_ports GPIO_DIP_SW0]
set_property IOSTANDARD SSTL15 [get_ports GPIO_DIP_SW0]