# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/KANG Jian/Desktop/PAM4-RGB-FPGA/control_test/cons/top_cons.xdc

# IP: C:/Users/KANG Jian/Desktop/PAM4-RGB-FPGA/control_test/ips/clk_gen/clk_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_gen || ORIG_REF_NAME==clk_gen} -quiet] -quiet
