# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/KANG Jian/Desktop/PAM4-RGB-FPGA/control_test/ips/clk_gen/clk_gen.xci
# IP: The module: 'clk_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/KANG Jian/Desktop/PAM4-RGB-FPGA/control_test/ips/clk_gen/clk_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/PAM4-RGB-FPGA/control_test/ips/clk_gen/clk_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/PAM4-RGB-FPGA/control_test/ips/clk_gen/clk_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/KANG Jian/Desktop/PAM4-RGB-FPGA/control_test/ips/clk_gen/clk_gen.xci
# IP: The module: 'clk_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/KANG Jian/Desktop/PAM4-RGB-FPGA/control_test/ips/clk_gen/clk_gen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/PAM4-RGB-FPGA/control_test/ips/clk_gen/clk_gen.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/KANG Jian/Desktop/PAM4-RGB-FPGA/control_test/ips/clk_gen/clk_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
